terramaid: disable autobump
Autobump disabled because upstram bumps it as needed:
https://github.com/RoseSecurity/Terramaid/blob/26ceb1eaae1a52b264f099dc9a7f37a6d2a5a08c/.github/workflows/build.yaml#L124-L127
```yaml
      - uses: dawidd6/action-homebrew-bump-formula@1446dca236b0440c6f02723a3f14f13be2c04ab0 # v7
        with:
          # A PR will be sent to github.com/Homebrew/homebrew-core to update this formula:
          formula: terramaid
```
and this was [failing](https://github.com/RoseSecurity/Terramaid/actions/runs/27016781794/job/79734376960#step:4:117) with:
```
Error: Whoops, the terramaid formula has its version update
pull requests automatically opened by BrewTestBot every ~3 hours!
We'd still love your contributions, though, so try another one
that is excluded from autobump list (i.e. it has 'no_autobump!'
method or 'livecheck' block with 'skip'.)
```

Spin-off from
* https://github.com/Homebrew/homebrew-core/pull/290269