zssh: disable `readline` due to incompatible license
Can keep on macOS as system `libedit` has modifications that improve
compatibility with `readline`. On Linux with brew `libedit`, it fails
```
completion.c:56:40: error: ‘CPPFunction’ undeclared (first use in this function)
```