gcc: link with -headerpad_max_install_names
Fixes an issue when using a non-default brew prefix where the
postinstall step can fail:

    Error: Failed changing dylib ID of /Users/example/homebrew/Cellar/gcc/15.2.0_1/lib/gcc/current/libatomic.1.dylib
      from @rpath/libatomic.1.dylib
        to /Users/example/homebrew/opt/gcc/lib/gcc/current/libatomic.1.dylib
    Error: Failed to fix install linkage
    Updated load commands do not fit in the header of /Users/example/homebrew/Cellar/gcc/15.2.0_1/lib/gcc/current/libatomic.1.dylib. /Users/example/homebrew/Cellar/gcc/15.2.0_1/lib/gcc/current/libatomic.1.dylib needs to be relinked, possibly with -headerpad or -headerpad_max_install_names