tronbyt-server: handle existing config files
Quick follow up on
https://github.com/Homebrew/homebrew-core/pull/259630:
only create the .env file if it doesn't exist to avoid this error on
upgrades:

```
Error: An exception occurred within a child process:
  RuntimeError: Will not overwrite /opt/homebrew/var/tronbyt-server/.env
```